[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["covid19_2"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "covid19_2"
  org = "aiteam"
  version = "3.1.2"

